djangotodo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from .views import (
    todo_list_view,
    insert_todo_view,
    delete_todo_view,
)

app_name = 'todos'
urlpatterns = [
    path('list/', todo_list_view, name='todo-list'),
    path('insert/', insert_todo_view, name='todo-insert'),
    path('delete/<int:id>', delete_todo_view, name='todo-delete'),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.TextField()

todos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from .models import Todo

# Create your views here.
def todo_list_view(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'todos/todo_list.html', context)

def insert_todo_view(request:HttpRequest):
    todo = Todo(content = request.POST['content'])
    todo.save()
    return redirect('/todos/list/')

def delete_todo_view(request, id):
    todo_delete = Todo.objects.get(id=id)
    todo_delete.delete()
    return redirect('/todos/list/')

todos/templates/todos/todo_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todos</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
</head>

{% load static %}

<body class="bg-light">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-8 offset-md-2">

                <div class="card">
                    <div class="card-header shadow-sm bg-white">
                        <h1 class="display-5 text-info"><i class="fas fa-check-double"></i> Todos</h1>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <form action="{% url 'todos:todo-insert' %}" method="POST" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="content">
                                        <div class="input-group-append text-info">
                                            <span class="input-group-text bg-white py-0">
                                                <button type="submit" class="btn btn-sm text-info">
                                                    <i class="fa fa-plus-circle fa-lg"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                </form>
                            </li>
                            {% for todo in todos %}
                            <li class="list-group-item">{{ todo.content }}
                                <form action="{% url 'todos:todo-delete' todo.id %}" method="POST" class="float-right d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn">
                                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                                    </button>
                                </form>
                            </li>
                            {% empty %}
                            <li class="list-group-item">
                                <span class="font-italic">No to do item found.</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>